default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: packrat_development
  host: db
  port: 5432
  username: postgres
  password: <%= ENV["DB_ENV_POSTGRES_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default
  database: packrat_test

production:
  <<: *default
  database: packrat_production
